### ISSUE TITLE
Automatically transpile ES6 files on change

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/generator-tabris-js#10]
After creating an ES6 style project, it would be great to develop without having to re-execute the build (transpile) step to get ES5 syntax from ES6.

I solved this for myself by doing the following:

`npm install npm-watch --save-dev`

And then inside `package.json`

```json
{
  "name": "com.hello.world",
  "version": "0.1.0",
  "main": "dist/app.js",
  "private": true,
  "watch": {
    "build:ios": "src/*.js"
  },
  "scripts": {
    "build:ios": "rm -rf dist/ && cp babel-ios.json .babelrc && babel --compact false --out-dir dist/ src/",
    "build:android": "rm -rf dist/ && cp babel-android.json .babelrc && babel --compact false --out-dir dist/ src/",
    "start": "http-server -c-1 -d false",
    "watch": "npm-watch"
  },
  "dependencies": {
    "tabris": "^1.10.0"
  },
  "devDependencies": {
    "npm-watch": "^0.1.7",
    "babel-cli": "^6.18.0",
    "babel-plugin-transform-es2015-arrow-functions": "^6.8.0",
    "babel-plugin-transform-es2015-block-scoping": "^6.21.0",
    "babel-plugin-transform-es2015-classes": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.18.0",
    "babel-plugin-transform-es2015-parameters": "^6.21.0",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.18.0",
    "babel-plugin-transform-es2015-spread": "^6.8.0",
    "babel-plugin-transform-es2015-template-literals": "^6.8.0"
  }
}
```

See also: https://www.npmjs.com/package/npm-watch

From there, I can use `npm run watch` in one shell tab, and `npm start` in another.

Changes to `.js` files are detected and rebuilt.

I am happy to do this in a PR if I get some +1's

**Comment by ralfstx** [comment]
Sounds good to me. I’m not sure how that scales for larger projects, where the build takes longer. A selective watch mode, that only re-compiles the parts that have changed, might be superior.

Unfortunately, I found Babel’s watch mode to be buggy at times. Once a file has been saved that contained a syntax error, it would not recover when the file is fixed but continue to produce defective code. Maybe this error is fixed meanwhile.

However, your solution is simple and it may be a good start. A PR would be nice.

**Comment by camstuart** [comment]
Yes agreed, selective transpile would be much better. 
I wonder if webpack would help? transpile and serve in one (and in the future, linting and testing?).

I might investigate that option and get a feel for what is involved

**Comment by camstuart** [comment]
No longer needed since #27 was resolved
