### ISSUE TITLE
Lock npm dependencies: shrinkwrap or yarn? 

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/generator-tabris-js#16]
The npm dependencies should be locked at known working versions. Application developers can then upgrade npm packages selectively in a controlled fashion as required.

This would apply to both the generator itself, and the generated output project.

There are two possible approaches to this that I am aware of:

1. Use `npm shrinkwrap` to produce a `npm-shrinkwrap.json` file
2. Switch to `yarn` which has it's own `yarn.lock` by default

I would normally favour option 2: `yarn` however, the tabris-js.com online build tool would need to detect that `yarn` is being used in place of npm

**Comment by tbuschto** [comment]
Issue moved to tabris-js-cli repo: https://github.com/eclipsesource/tabris-js-cli/issues/12
