### ISSUE TITLE
"build:..." script names may be confusing

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/generator-tabris-js#17]
It is not self-explanatory what the difference between a build script and a Cordova build is. To make it more clear, package.json script names like "compile" or "transpile" can be used instead, as those scripts do nothing more than transpile app code (ES6 -> ES5, TS -> ES5), i.e. no executable app is "built". "compile" might be a more accurate term, since in the future those scripts might include additional tasks like bundling and minification.

**Comment by ralfstx** [comment]
:+1: for telling names, however, the build server will automatically execute a script named `build` or `build:<platform>` if present, so we have to keep those.

**Comment by tbuschto** [comment]
The package.json build scripts are PART of the entire build process. This could be documented better, which is another issue.
