### ISSUE TITLE
Invalid package name for Android

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/generator-tabris-js#26]
In a directory named `foo`, the generator would create a `config.xml` with the id `foo` (`<widget id="foo" ...`). This appears to be an invalid package id on Android:

```
$ cordova platform add /path/to/tabris-android
Adding android project...
Error: Error validating package name. Package name must look like: com.company.Name
```

Changing it to `example.foo` works.

**Comment by camstuart** [comment]
So what's the rule here, require a minimum of two strings separated by a period?

**Comment by ralfstx** [comment]
Yeah, seems that at least a single period is required. I'm working on a change.
