### ISSUE TITLE
Remove the Basic JS example

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/generator-tabris-js#27]
The current choice of project types to create may be confusing for beginners:

* Basic JS App
* ES6 App (using Babel transpiler)
* TypeScript App

With iOS 8 and 9 being the last Tabris.js platforms that don't support ES6, and those are quickly losing market share, it seems to be a good time to move forward to ES6 and not advertise ES5 anymore.

I'd suggest to reduce the project types to:

* JavaScript App
* TypeScript App

The JavaScript App should be based on ES6. If we use `require` instead of `import`, we should not need a transpile step anymore.

**Comment by camstuart** [comment]
I will tackle this one
