### ISSUE TITLE
Add taks.json to support Visual Studio Code

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/generator-tabris-js#32]
VS code has a task runner that can be easily mapped to the npm scripts we use. We can simply add `.vscode/tasks.json` to have an entry for each relevant npm script like this:

```
{

  "version": "0.1.0",
  "command": "npm",
  "isShellCommand": true,
  "tasks": [
    {
      "taskName": "start"
    }
  ]
}
```

**Comment by cpetrov** [comment]
`tasks.json` introduced in https://github.com/eclipsesource/generator-tabris-js/commit/da2755d991ad612d32fec49c89b6eeb3a4317faf
