### ISSUE TITLE
Switch from TSLint to ESLint

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/generator-tabris-js#39]
From [TypeScript Roadmap: January - June 2019](https://github.com/Microsoft/TypeScript/issues/29288#Linting):

> In a survey we ran in VS Code a few months back, the most frequent theme we heard from users was that the linting experience left much to be desired. Since part of our team is dedicated to editing experiences in JavaScript, our editor team set out to add support for both TSLint and ESLint. However, we noticed that there were a few architectural issues with the way TSLint rules operate that impacted performance. Fixing TSLint to operate more efficiently would require a different API which would break existing rules (unless an interop API was built like what [wotan](https://github.com/fimbullinter/wotan/) provides).
>
> Meanwhile, ESLint already has the more-performant architecture we're looking for from a linter. Additionally, different communities of users often have lint rules (e.g. rules for React Hooks or Vue) that are built for ESLint, but not TSLint.
>
> Given this, our editor team will be focusing on leveraging ESLint rather than duplicating work. For scenarios that ESLint currently doesn't cover (e.g. semantic linting or program-wide linting), we'll be working on sending contributions to bring ESLint's TypeScript support to parity with TSLint. As an initial testbed of how this works in practice, we'll be switching the TypeScript repository over to using ESLint, and sending any new rules upstream.

**Comment by mpost** [comment]
Is it already usable in production?

**Comment by tbuschto** [comment]
TS-Lint is now deprecated

**Comment by tbuschto** [comment]
We migrated the core module to eslint. But this included several eslint plug-ins to handle TypeScript and JSX. This seems overkill to include in a every generated project, especially when it is tsc-compiled, but not TypeScript. How should we handle this? Do we need an extra configuration step?

**Comment by tbuschto** [comment]
We did do the overkill variant. Issue closed.
