### ISSUE TITLE
package.json should contain dev-dependency on Cordova

### ISSUE THREAD

**Issue by jonek** [eclipsesource/generator-tabris-js#5]
To build the generated project locally, users need Cordova.

Add it as a dev-dependency.

**Comment by ralfstx** [comment]
Cordova is a huge dependency. We should avoid adding this dependency to every new Tabris.js project.

It should rather be a dependency of the [CLI](/eclipsesource/tabris-js-cli/). Since you'd install the CLI globally, you'd also have this dependency only once.
