### ISSUE TITLE
No mechanism to create required project structure for local build

### ISSUE THREAD

**Issue by jonek** [eclipsesource/generator-tabris-js#6]
As a developer I want to build my app locally.
Therefor I need some kind of build script that can create the required project structure (cordova/www with my app.js and apckage.json inside).
This build script should at least create the cordova/www folder and copy the app.js and package.json to that directory as those files are generated by the yeoman template.

**Comment by ralfstx** [comment]
This should be a responsibility of the Tabris [CLI](/eclipsesource/tabris-js-cli/). Opened https://github.com/eclipsesource/tabris-js-cli/issues/1
