### ISSUE TITLE
Add widget.id validation

### ISSUE THREAD

**Issue by fwaibel** [eclipsesource/generator-tabris-js#8]
I created a test project https://github.com/eclipsesource/tabris-js-hello-world with `hello-world` which seems to be invalid.

**Comment by fwaibel** [comment]
<img width="712" alt="screen shot 2016-12-14 at 12 58 04" src="https://cloud.githubusercontent.com/assets/539039/21181243/3d6ff330-c1fd-11e6-81e2-4498ca3954b4.png">

**Comment by irbull** [comment]
@fwaibel Can you post value of `widget.id`?

**Comment by mpost** [comment]
the id would have been `hello-world` but the dash is proly not allowed.

**Comment by mpost** [comment]
Ups didn't mean to close.

**Comment by fwaibel** [comment]
Yes, this commit fixed the `hello-world` https://github.com/eclipsesource/tabris-js-hello-world/commit/7a99beb5384d2c531c0d623afac0df74c701d475
